version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_PASSWORD: super-secret-prod-password
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_PASSWORD: super-secret-prod-password
